code --install-extension --force betterthantomorrow.calva
code --install-extension --force betterthantomorrow.calva-spritz
code --install-extension --force dracula-theme.theme-dracula
code --install-extension --force eamodio.gitlens
code --install-extension --force github.copilot
code --install-extension --force github.copilot-chat
code --install-extension --force mechatroner.rainbow-csv
code --install-extension --force ms-vscode.makefile-tools
code --install-extension --force redhat.java
code --install-extension --force scala-lang.scala
code --install-extension --force shd101wyy.markdown-preview-enhanced
code --install-extension --force tal7aouy.icons
code --install-extension --force tyriar.sort-lines
code --install-extension --force usernamehw.errorlens
code --install-extension --force visualstudioexptteam.intellicode-api-usage-examples
code --install-extension --force visualstudioexptteam.vscodeintellicode
code --install-extension --force vscjava.vscode-gradle
code --install-extension --force vscjava.vscode-java-debug
code --install-extension --force vscjava.vscode-java-dependency
code --install-extension --force vscjava.vscode-java-pack
code --install-extension --force vscjava.vscode-java-test
code --install-extension --force vscjava.vscode-maven
code --install-extension --force vscode-icons-team.vscode-icons
code --install-extension --force wayou.vscode-todo-highlight
code --install-extension --force wmaurer.change-case
