code --install-extension --force adpyke.vscode-sql-formatter
code --install-extension --force afractal.node-essentials
code --install-extension --force be5invis.vscode-icontheme-nomo-dark
code --install-extension --force betterthantomorrow.calva
code --install-extension --force betterthantomorrow.calva-spritz
code --install-extension --force christian-kohler.path-intellisense
code --install-extension --force dracula-theme.theme-dracula
code --install-extension --force eamodio.gitlens
code --install-extension --force editorconfig.editorconfig
code --install-extension --force github.vscode-pull-request-github
code --install-extension --force jakebecker.elixir-ls
code --install-extension --force lixquid.calculator
code --install-extension --force mechatroner.rainbow-csv
code --install-extension --force mikestead.dotenv
code --install-extension --force ms-azuretools.vscode-docker
code --install-extension --force ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension --force ms-python.debugpy
code --install-extension --force ms-python.python
code --install-extension --force ms-python.vscode-pylance
code --install-extension --force ms-vscode.vscode-typescript-tslint-plugin
code --install-extension --force ms-vsliveshare.vsliveshare
code --install-extension --force oderwat.indent-rainbow
code --install-extension --force orta.vscode-jest
code --install-extension --force redhat.fabric8-analytics
code --install-extension --force redhat.vscode-yaml
code --install-extension --force ritwickdey.liveserver
code --install-extension --force rvest.vs-code-prettier-eslint
code --install-extension --force shd101wyy.markdown-preview-enhanced
code --install-extension --force visualstudioexptteam.intellicode-api-usage-examples
code --install-extension --force visualstudioexptteam.vscodeintellicode
code --install-extension --force vscode-icons-team.vscode-icons
code --install-extension --force wallabyjs.quokka-vscode
code --install-extension --force wix.vscode-import-cost
code --install-extension --force wmaurer.change-case
