code --install-extension acarreiro.calculate
code --install-extension adpyke.vscode-sql-formatter
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension iampeterbanjo.elixirlinter
code --install-extension IronGeek.vscode-env
code --install-extension JakeBecker.elixir-ls
code --install-extension mechatroner.rainbow-csv
code --install-extension mohsen1.prettify-json
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension naumovs.color-highlight
code --install-extension oderwat.indent-rainbow
code --install-extension ritwickdey.LiveServer
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wmaurer.change-case
